const desserts = [
    {
      category: "Chocolate Desserts",
      items: [
        {
          name: "Chocolate Cake",
          image: "https://images.pexels.com/photos/4109996/pexels-photo-4109996.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
          recipe: " <h4>Chocolate Cake Recipe</h4><h5>Ingredients:</h5><ul><li>1 and 3/4 cups (220g) all-purpose flour</li><li>3/4 cup (65g) unsweetened cocoa powder</li><li>2 cups (400g) granulated sugar</li><li>1 and 1/2 tsp baking powder</li><li>1 and 1/2 tsp baking soda</li><li>1 tsp salt</li><li>2 large eggs</li><li>1 cup (240ml) milk</li><li>1/2 cup (120ml) vegetable oil</li><li>2 tsp vanilla extract</li><li>1 cup (240ml) boiling water or hot coffee (for richer flavor)</li></ul><h5>Instructions:</h5><ol><li>Preheat oven to 350°F (175°C). Grease and flour two 9-inch round cake pans.</li><li>In a large bowl, sift together flour, cocoa powder, sugar, baking powder, baking soda, and salt.</li><li>Add eggs, milk, oil, and vanilla extract. Beat on medium speed for 2 minutes.</li><li>Stir in hot water or coffee (batter will be thin). Pour evenly into prepared pans.</li><li>Bake for 30–35 minutes or until a toothpick inserted in the center comes out clean.</li><li>Cool in pans for 10 minutes, then remove and cool completely on a wire rack.</li></ol><h5>Chocolate Frosting:</h5><ul><li>1 cup (230g) unsalted butter, softened</li><li>3 and 1/2 cups (440g) powdered sugar</li><li>1/2 cup (45g) cocoa powder</li><li>1/2 tsp salt</li><li>2 tsp vanilla extract</li><li>1/4 cup (60ml) heavy cream or milk (adjust for consistency)</li></ul><p>Beat all frosting ingredients together until smooth and fluffy. Spread over cooled cake layers.</p><strong>Tip:</strong> Add chocolate chips between the layers or top with chocolate shavings for extra decadence!"
        },
        {
          name: "Brownies",
          image: "https://images.pexels.com/photos/2067396/pexels-photo-2067396.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
          recipe: "<h4>Fudgy Chocolate Brownies Recipe</h4>\n<h5>Ingredients:</h5>\n<ul>\n<li>1/2 cup (115g) unsalted butter</li>\n<li>1 tablespoon (15ml) vegetable oil (for extra moistness)</li>\n<li>1 cup (200g) granulated sugar</li>\n<li>2 large eggs</li>\n<li>1 teaspoon vanilla extract</li>\n<li>1/3 cup (40g) unsweetened cocoa powder</li>\n<li>1/2 cup (65g) all-purpose flour</li>\n<li>1/4 teaspoon salt</li>\n<li>1/4 teaspoon baking powder</li>\n<li>1/2 cup (90g) chocolate chips or chunks (optional but recommended)</li>\n</ul>\n<h5>Instructions:</h5>\n<ol>\n<li>Preheat your oven to 350°F (175°C). Grease or line an 8x8-inch (20x20 cm) baking pan with parchment paper.</li>\n<li>Melt butter in a medium saucepan over low heat. Remove from heat and stir in sugar and oil until smooth.</li>\n<li>Whisk in eggs and vanilla extract until fully combined and slightly fluffy.</li>\n<li>Sift in cocoa powder, flour, salt, and baking powder. Stir gently until just combined (do not overmix).</li>\n<li>Fold in chocolate chips or chunks if using.</li>\n<li>Pour batter into prepared pan and smooth the top with a spatula.</li>\n<li>Bake for 20–25 minutes, or until the edges are firm and the center is just set (a toothpick should come out with moist crumbs, not wet batter).</li>\n<li>Allow to cool completely in the pan before slicing into squares.</li>\n</ol>\n<h5>Optional Add-ins:</h5>\n<ul>\n<li>Chopped walnuts or pecans for crunch</li>\n<li>Swirl in cream cheese or peanut butter for a fun twist</li>\n<li>Top with a sprinkle of sea salt before baking for a sweet-salty vibe</li>\n</ul>\n<strong>Tip:</strong> For even fudgier brownies, refrigerate after baking and serve chilled. They're extra dense and chocolatey that way!"
        },
        {
            name: "Classic Chocolate Mousse",
            image: "https://images.pexels.com/photos/3026810/pexels-photo-3026810.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
            recipe: "<h4>Classic Chocolate Mousse Recipe</h4>\n<h5>Ingredients:</h5>\n<ul>\n<li>200g (7 oz) dark chocolate (around 70% cocoa), chopped</li>\n<li>3 large eggs, separated</li>\n<li>1/4 cup (50g) granulated sugar</li>\n<li>1 teaspoon vanilla extract</li>\n<li>1 cup (240ml) heavy cream (chilled)</li>\n<li>Pinch of salt</li>\n<li>Optional toppings: whipped cream, shaved chocolate, berries, or mint leaves</li>\n</ul>\n<h5>Instructions:</h5>\n<ol>\n<li>Melt the chopped chocolate using a double boiler or microwave in short intervals (30 sec bursts). Stir until smooth, then set aside to cool slightly.</li>\n<li>In a clean bowl, beat the egg whites with a pinch of salt until soft peaks form. Gradually add half the sugar and beat until glossy stiff peaks form. Set aside.</li>\n<li>In another bowl, whisk egg yolks with the remaining sugar and vanilla until light and creamy (about 2–3 minutes).</li>\n<li>Gently fold the melted chocolate into the yolk mixture until combined.</li>\n<li>In a chilled bowl, whip the heavy cream to soft peaks. Set aside 1/4 cup for topping (optional).</li>\n<li>Gently fold the whipped cream into the chocolate mixture in two parts.</li>\n<li>Now gently fold in the beaten egg whites in 2-3 additions until the mousse is smooth and airy (don’t overmix).</li>\n<li>Spoon the mousse into serving glasses or bowls and refrigerate for at least 2 hours (or overnight) to set.</li>\n<li>Before serving, top with extra whipped cream, chocolate shavings, or fresh berries if desired.</li>\n</ol>\n<strong>Tip:</strong> For a richer version, add a splash of espresso or coffee liqueur to the melted chocolate. It enhances the chocolate flavor beautifully!"
          },
          {
            name: "Chocolate Truffles",
            image: "https://images.pexels.com/photos/31583805/pexels-photo-31583805/free-photo-of-elegant-strawberry-and-chocolate-dessert-bowl.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
            recipe: "<h4>Chocolate Truffles Recipe</h4>\n<h5>Ingredients:</h5>\n<ul>\n<li>200g (7 oz) dark or semi-sweet chocolate, finely chopped</li>\n<li>100ml (about 1/2 cup) heavy cream</li>\n<li>1 tbsp unsalted butter (optional, for extra smoothness)</li>\n<li>1 tsp vanilla extract or 1 tbsp liqueur (e.g., rum, Baileys, optional)</li>\n<li>Cocoa powder, chopped nuts, shredded coconut, or melted chocolate for coating</li>\n</ul>\n<h5>Instructions:</h5>\n<ol>\n<li>Heat the cream in a small saucepan over medium heat until it just begins to simmer (do not boil).</li>\n<li>Remove from heat and pour over the chopped chocolate in a bowl. Let sit for 1–2 minutes, then stir until smooth.</li>\n<li>Stir in butter and vanilla (or liqueur) if using. Mix until fully combined and glossy.</li>\n<li>Cover the bowl with plastic wrap and refrigerate for 1–2 hours, or until the ganache is firm enough to scoop.</li>\n<li>Using a small spoon or melon baller, scoop out portions and roll them into balls with your hands (wear gloves or dust hands with cocoa powder).</li>\n<li>Roll each truffle in your preferred coating: cocoa powder, chopped nuts, coconut, or drizzle/dip in melted chocolate.</li>\n<li>Place finished truffles on a tray lined with parchment and chill until set (about 30 minutes).</li>\n<li>Store in an airtight container in the refrigerator for up to 1 week, or freeze for longer storage.</li>\n</ol>\n<strong>Tip:</strong> For a professional look, use different coatings for variety and place truffles in mini paper cups before serving!"
          }          
      ]
    },
    {
      category: "Fruit Desserts",
      items: [
        {
            name: "Strawberry Cheesecake",
            image: "https://images.pexels.com/photos/1126359/pexels-photo-1126359.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
            recipe: "<h4>Strawberry Cheesecake Recipe</h4>\n<h5>Ingredients:</h5>\n<ul>\n<li><strong>For the crust:</strong></li>\n<li>1 1/2 cups (150g) graham cracker crumbs or digestive biscuit crumbs</li>\n<li>1/4 cup (50g) granulated sugar</li>\n<li>1/2 cup (115g) melted butter</li>\n<li><strong>For the filling:</strong></li>\n<li>450g (16 oz) cream cheese, softened</li>\n<li>3/4 cup (150g) granulated sugar</li>\n<li>1 tsp vanilla extract</li>\n<li>2 large eggs</li>\n<li>1/2 cup (120g) sour cream or Greek yogurt</li>\n<li><strong>For the topping:</strong></li>\n<li>1 cup fresh strawberries, hulled and sliced</li>\n<li>1/4 cup (50g) sugar</li>\n<li>1 tsp lemon juice</li>\n</ul>\n<h5>Instructions:</h5>\n<ol>\n<li>Preheat your oven to 325°F (160°C). Grease or line a springform pan.</li>\n<li>Mix graham cracker crumbs, sugar, and melted butter. Press into the bottom of the pan to form a crust. Bake for 10 minutes and let it cool.</li>\n<li>In a large bowl, beat the cream cheese until smooth. Add sugar and vanilla; mix until well combined.</li>\n<li>Add eggs one at a time, mixing well after each. Then stir in sour cream/yogurt until smooth.</li>\n<li>Pour the filling over the cooled crust. Smooth the top with a spatula.</li>\n<li>Bake for 45–50 minutes or until the center is just set. Turn off the oven and let cheesecake sit inside with door slightly open for 1 hour.</li>\n<li>Chill in the refrigerator for at least 4 hours or overnight.</li>\n<li>In a saucepan, combine strawberries, sugar, and lemon juice. Cook over medium heat until strawberries break down and sauce thickens slightly (about 10–12 minutes). Cool before topping the cheesecake.</li>\n<li>Spoon the strawberry topping over the chilled cheesecake before serving.</li>\n</ol>\n<strong>Tip:</strong> Add a dollop of whipped cream and extra strawberries for a fancy finish!"
          },
          {
            name: "Apple Pie",
            image: "https://images.pexels.com/photos/6163263/pexels-photo-6163263.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
            recipe: "<h4>Apple Pie Recipe</h4>\n<h5>Ingredients:</h5>\n<ul>\n<li><strong>For the crust:</strong></li>\n<li>2 1/2 cups (315g) all-purpose flour</li>\n<li>1 tsp salt</li>\n<li>1 tbsp sugar</li>\n<li>1 cup (225g) cold unsalted butter, cubed</li>\n<li>6–8 tbsp ice water</li>\n<li><strong>For the filling:</strong></li>\n<li>6 cups (about 6 medium) thinly sliced peeled apples (Granny Smith or Honeycrisp work great)</li>\n<li>3/4 cup (150g) granulated sugar</li>\n<li>1/4 cup (30g) all-purpose flour</li>\n<li>1 tsp ground cinnamon</li>\n<li>1/4 tsp ground nutmeg</li>\n<li>1 tbsp lemon juice</li>\n<li>1 tbsp butter (for dotting the filling)</li>\n</ul>\n<h5>Instructions:</h5>\n<ol>\n<li><strong>Make the crust:</strong> In a large bowl, mix flour, salt, and sugar. Cut in cold butter using a pastry cutter or fork until mixture resembles coarse crumbs.</li>\n<li>Add ice water, one tablespoon at a time, mixing just until the dough comes together. Divide in two, shape into disks, wrap, and chill for at least 1 hour.</li>\n<li><strong>Prepare the filling:</strong> In a bowl, combine sliced apples, sugar, flour, cinnamon, nutmeg, and lemon juice. Toss well to coat.</li>\n<li>Preheat oven to 425°F (220°C). Roll out one dough disk and fit into a 9-inch pie dish. Trim excess dough from edges.</li>\n<li>Spoon the apple filling into the crust and dot with butter.</li>\n<li>Roll out second dough disk and place over the filling. Trim, seal, and crimp the edges. Cut small slits on top to vent steam.</li>\n<li>Optionally, brush with egg wash (1 egg beaten with 1 tbsp water) for a golden finish and sprinkle with sugar.</li>\n<li>Bake for 45–50 minutes or until the crust is golden and filling is bubbling. Cover edges with foil if they brown too quickly.</li>\n<li>Let cool for at least 2 hours before serving for best slicing.</li>\n</ol>\n<strong>Tip:</strong> Serve warm with a scoop of vanilla ice cream!"
          },          
          {
            name: "Peach Cobbler",
            image: "https://images.pexels.com/photos/19910615/pexels-photo-19910615/free-photo-of-cake-with-fruit-slices.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
            recipe: "<h4>Peach Cobbler Recipe</h4>\n<h5>Ingredients:</h5>\n<ul>\n<li><strong>For the filling:</strong></li>\n<li>5 cups sliced fresh peaches (or use drained canned peaches)</li>\n<li>3/4 cup (150g) granulated sugar</li>\n<li>1/4 cup (30g) brown sugar</li>\n<li>1/4 tsp salt</li>\n<li>1 tsp lemon juice</li>\n<li>1/2 tsp ground cinnamon</li>\n<li>1/4 tsp ground nutmeg</li>\n<li>1 tbsp cornstarch (optional for thickening)</li>\n<li><strong>For the topping:</strong></li>\n<li>1 cup (125g) all-purpose flour</li>\n<li>1/4 cup (50g) granulated sugar</li>\n<li>1/4 cup (55g) brown sugar</li>\n<li>1 tsp baking powder</li>\n<li>1/2 tsp salt</li>\n<li>6 tbsp (85g) unsalted butter, chilled and diced</li>\n<li>1/4 cup boiling water</li>\n<li><strong>Optional Cinnamon Sugar Topping:</strong></li>\n<li>3 tbsp sugar mixed with 1 tsp cinnamon</li>\n</ul>\n<h5>Instructions:</h5>\n<ol>\n<li>Preheat oven to 375°F (190°C). Grease a 9x13-inch baking dish.</li>\n<li>In a large bowl, combine peaches, both sugars, salt, lemon juice, cinnamon, nutmeg, and cornstarch. Stir well and pour into prepared baking dish.</li>\n<li>To make the topping, combine flour, sugars, baking powder, and salt in a bowl. Cut in butter using a pastry cutter or fork until mixture resembles coarse crumbs.</li>\n<li>Add boiling water and stir just until combined. Drop spoonfuls of the dough over the peach mixture. It doesn’t need to fully cover the fruit.</li>\n<li>Sprinkle cinnamon sugar topping (if using) evenly over the cobbler dough.</li>\n<li>Bake for 40–45 minutes until the top is golden brown and the filling is bubbling around the edges.</li>\n<li>Let it cool slightly before serving. Best served warm with vanilla ice cream!</li>\n</ol>\n<strong>Tip:</strong> You can use frozen peaches — just thaw and drain them first!"
          },
          {
            name: "Berry Parfait",
            image: "https://images.pexels.com/photos/1510693/pexels-photo-1510693.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
            recipe: "<h4>Berry Parfait Recipe</h4>\n<h5>Ingredients:</h5>\n<ul>\n<li>1 cup strawberries, hulled and sliced</li>\n<li>1 cup blueberries</li>\n<li>1 cup raspberries</li>\n<li>2 cups vanilla Greek yogurt (or regular yogurt)</li>\n<li>1/2 cup granola (store-bought or homemade)</li>\n<li>1 tbsp honey or maple syrup (optional)</li>\n<li>Fresh mint leaves for garnish (optional)</li>\n</ul>\n<h5>Instructions:</h5>\n<ol>\n<li>Wash and prepare all the berries. If needed, pat them dry to avoid sogginess.</li>\n<li>In a glass or dessert cup, add a spoonful of yogurt as the base layer.</li>\n<li>Add a layer of mixed berries, followed by a layer of granola.</li>\n<li>Repeat the layers until the glass is full or ingredients are used up, finishing with a few berries on top.</li>\n<li>Drizzle with honey or maple syrup if desired.</li>\n<li>Garnish with fresh mint leaves for an extra fresh touch.</li>\n<li>Serve immediately for a crunchy parfait or refrigerate for 15–20 minutes if you prefer it chilled and slightly softened.</li>\n</ol>\n<strong>Tip:</strong> You can mix in chia seeds, nuts, or use flavored yogurt for variety!"
          }          
      ]
    },
    {
      category: "Frozen Desserts",
      items: [
        {
            name: "Vanilla Ice Cream",
            image: "https://images.pexels.com/photos/1352278/pexels-photo-1352278.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
            recipe: "<h4>Vanilla Ice Cream Recipe</h4>\n<h5>Ingredients:</h5>\n<ul>\n<li>2 cups heavy cream</li>\n<li>1 cup whole milk</li>\n<li>3/4 cup granulated sugar</li>\n<li>1 tablespoon pure vanilla extract</li>\n<li>Pinch of salt</li>\n</ul>\n<h5>Instructions:</h5>\n<ol>\n<li>In a mixing bowl, whisk together the milk and sugar until the sugar is dissolved.</li>\n<li>Add the heavy cream, vanilla extract, and a pinch of salt. Stir until well combined.</li>\n<li>Cover the bowl and refrigerate the mixture for at least 2 hours or until thoroughly chilled.</li>\n<li>Pour the chilled mixture into your ice cream maker and churn according to the manufacturer's instructions (usually 20–25 minutes).</li>\n<li>Once the ice cream reaches a soft-serve consistency, transfer it to an airtight container.</li>\n<li>Freeze for at least 4 hours or until firm.</li>\n<li>Scoop and serve plain, or top with chocolate syrup, fruits, or sprinkles.</li>\n</ol>\n<strong>Tip:</strong> For extra creaminess, use a higher ratio of cream to milk, or fold in whipped cream before freezing!"
          },
          {
            name: "Mango Sorbet",
            image: "https://images.pexels.com/photos/5060372/pexels-photo-5060372.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
            recipe: "<h4>Mango Sorbet Recipe</h4>\n<h5>Ingredients:</h5>\n<ul>\n<li>3 cups ripe mango chunks (fresh or frozen)</li>\n<li>1/2 cup granulated sugar</li>\n<li>1/2 cup water</li>\n<li>1 tablespoon lime juice</li>\n<li>Optional: pinch of salt</li>\n</ul>\n<h5>Instructions:</h5>\n<ol>\n<li>In a saucepan, combine sugar and water. Heat until sugar is dissolved to make a simple syrup. Let it cool completely.</li>\n<li>In a blender, add the mango chunks, cooled syrup, lime juice, and a pinch of salt (if using).</li>\n<li>Blend until smooth and creamy.</li>\n<li>Pour the mixture into an ice cream maker and churn for 20–25 minutes, or until it reaches a sorbet-like texture.</li>\n<li>Transfer to a container and freeze for at least 2 hours to firm up.</li>\n<li>Scoop and serve chilled. Garnish with fresh mint or mango slices if desired.</li>\n</ol>\n<strong>Tip:</strong> For a more intense mango flavor, reduce the water or add a splash of mango juice!"
          },
          {
            name: "Strawberry Gelato",
            image: "https://images.pexels.com/photos/5061027/pexels-photo-5061027.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
            recipe: "<h4>Strawberry Gelato Recipe</h4>\n<h5>Ingredients:</h5>\n<ul>\n<li>2 cups fresh strawberries, hulled and halved</li>\n<li>1 cup whole milk</li>\n<li>1 cup heavy cream</li>\n<li>3/4 cup granulated sugar</li>\n<li>1 teaspoon vanilla extract</li>\n<li>1 tablespoon lemon juice</li>\n</ul>\n<h5>Instructions:</h5>\n<ol>\n<li>Puree the strawberries in a blender or food processor until smooth. Set aside.</li>\n<li>In a medium saucepan, combine milk, cream, and sugar. Heat over medium heat, stirring occasionally until the sugar dissolves completely.</li>\n<li>Once the milk mixture is warm, add the strawberry puree, vanilla extract, and lemon juice. Stir to combine and heat for an additional 3-5 minutes, but do not let it boil.</li>\n<li>Remove from heat and let the mixture cool to room temperature. Once cooled, cover and refrigerate for at least 4 hours, or overnight for best results.</li>\n<li>Pour the cooled mixture into your ice cream maker and churn according to the manufacturer’s instructions, usually 20-25 minutes.</li>\n<li>Once the gelato reaches a thick, soft-serve consistency, transfer it to a container and freeze for 1-2 hours to firm up.</li>\n<li>Serve chilled, and enjoy the creamy, fruity goodness!</li>\n</ol>\n<strong>Tip:</strong> For an extra smooth texture, you can strain the strawberry puree before mixing it with the milk mixture to remove seeds."
          },
          {
            name: "Frozen Yogurt",
            image: "https://images.pexels.com/photos/2955817/pexels-photo-2955817.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
            recipe: "<h4>Frozen Yogurt Recipe</h4>\n<h5>Ingredients:</h5>\n<ul>\n<li>2 cups plain Greek yogurt</li>\n<li>1/2 cup honey</li>\n<li>1 teaspoon vanilla extract</li>\n<li>1/4 cup fresh fruit (optional, for topping)</li>\n</ul>\n<h5>Instructions:</h5>\n<ol>\n<li>In a mixing bowl, combine Greek yogurt, honey, and vanilla extract. Stir until smooth and well combined.</li>\n<li>For a tangier taste, you can use unsweetened yogurt or adjust the amount of honey to your preference.</li>\n<li>Pour the yogurt mixture into your ice cream maker, and churn according to the manufacturer’s instructions, about 20-30 minutes.</li>\n<li>Once the yogurt reaches a thick, soft-serve consistency, transfer it to a container.</li>\n<li>Freeze the yogurt for 4 hours to set. For a firmer consistency, leave it in the freezer for up to 6 hours.</li>\n<li>Serve the frozen yogurt with fresh fruit or any toppings of your choice.</li>\n</ol>\n<strong>Tip:</strong> If you don't have an ice cream maker, you can also spread the yogurt mixture in a shallow pan and freeze it. Stir every 30 minutes for the first 2-3 hours to keep the texture smooth."
          }          
      ]
    },
    {
      category: "Pastries and Bakes",
      items: [
        {
            name: "Croissant Pudding",
            image: "https://images.pexels.com/photos/1510682/pexels-photo-1510682.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
            recipe: "<h4>Croissant Pudding Recipe</h4>\n<h5>Ingredients:</h5>\n<ul>\n<li>4-5 stale croissants (or fresh, cut into pieces)</li>\n<li>2 cups whole milk</li>\n<li>1 cup heavy cream</li>\n<li>3/4 cup sugar</li>\n<li>4 large eggs</li>\n<li>1 tablespoon vanilla extract</li>\n<li>1 teaspoon cinnamon (optional)</li>\n<li>1/4 cup raisins (optional)</li>\n<li>Butter (for greasing the dish)</li>\n</ul>\n<h5>Instructions:</h5>\n<ol>\n<li>Preheat the oven to 350°F (175°C) and grease a baking dish with butter.</li>\n<li>Cut croissants into bite-sized pieces and place them in the greased dish. If using raisins, sprinkle them between the croissant layers.</li>\n<li>In a bowl, whisk together the milk, heavy cream, sugar, eggs, vanilla extract, and cinnamon until well combined.</li>\n<li>Pour the egg mixture evenly over the croissants. Use a spoon to gently press the croissants down so they soak up the liquid. Let it sit for 10-15 minutes to absorb.</li>\n<li>Bake in the preheated oven for 40-45 minutes, or until the pudding is golden brown and set. You can check doneness by inserting a knife into the center; it should come out clean.</li>\n<li>Allow the pudding to cool slightly before serving. It can be served warm or at room temperature.</li>\n<li>Optionally, dust with powdered sugar or drizzle with caramel sauce for extra flavor.</li>\n</ol>\n<strong>Tip:</strong> This dessert can be made ahead of time and stored in the refrigerator. Simply reheat before serving for a comforting treat."
          },
          {
            name: "Lemon Tart",
            image: "https://images.pexels.com/photos/8104732/pexels-photo-8104732.jpeg?auto=compress&cs=tinysrgb&w=600",
            recipe: "<h4>Lemon Tart Recipe</h4>\n<h5>Ingredients for the crust:</h5>\n<ul>\n<li>1 1/4 cups all-purpose flour</li>\n<li>1/4 cup powdered sugar</li>\n<li>1/2 teaspoon salt</li>\n<li>1/2 cup unsalted butter, chilled and cubed</li>\n<li>1 egg yolk</li>\n<li>1 tablespoon ice water (if needed)</li>\n</ul>\n<h5>Ingredients for the lemon filling:</h5>\n<ul>\n<li>3 large eggs</li>\n<li>1 cup granulated sugar</li>\n<li>1/2 cup freshly squeezed lemon juice (about 3 lemons)</li>\n<li>1/4 cup heavy cream</li>\n<li>1 tablespoon lemon zest</li>\n<li>1/4 teaspoon salt</li>\n</ul>\n<h5>Instructions:</h5>\n<ol>\n<li>Preheat your oven to 375°F (190°C).</li>\n<li>For the crust: In a food processor, combine flour, powdered sugar, and salt. Add the chilled butter and pulse until the mixture resembles coarse crumbs. Add the egg yolk and pulse until the dough starts to come together. If necessary, add ice water 1 tablespoon at a time.</li>\n<li>Turn the dough onto a lightly floured surface and knead briefly until smooth. Shape the dough into a disk, wrap in plastic, and refrigerate for at least 30 minutes.</li>\n<li>Once chilled, roll the dough out to fit a 9-inch tart pan. Press the dough into the pan, trimming any excess. Prick the bottom with a fork and refrigerate again for 15 minutes to prevent shrinking during baking.</li>\n<li>Bake the crust for 15-18 minutes or until lightly golden. Set aside to cool while you prepare the filling.</li>\n<li>For the filling: In a medium bowl, whisk together the eggs and sugar until smooth. Add lemon juice, lemon zest, heavy cream, and salt. Whisk until well combined.</li>\n<li>Pour the lemon filling into the cooled tart crust and bake for an additional 20-25 minutes, or until the filling is set and slightly golden around the edges. The center should still have a slight jiggle.</li>\n<li>Let the tart cool completely at room temperature. Once cooled, refrigerate for at least 2 hours before serving.</li>\n<li>Serve chilled, garnished with extra lemon zest or fresh whipped cream if desired.</li>\n</ol>\n<strong>Tip:</strong> You can make the crust and filling ahead of time and store them separately in the fridge until you’re ready to assemble the tart."
          },
          {
            name: "Banana Bread",
            image: "https://images.pexels.com/photos/830894/pexels-photo-830894.jpeg?auto=compress&cs=tinysrgb&w=600",
            recipe: "<h4>Banana Bread Recipe</h4>\n<h5>Ingredients:</h5>\n<ul>\n<li>3 ripe bananas</li>\n<li>1/3 cup melted butter</li>\n<li>1 teaspoon baking soda</li>\n<li>Pinch of salt</li>\n<li>3/4 cup sugar (can reduce for less sweetness)</li>\n<li>1 large egg, beaten</li>\n<li>1 teaspoon vanilla extract</li>\n<li>1 1/2 cups all-purpose flour</li>\n</ul>\n<h5>Instructions:</h5>\n<ol>\n<li>Preheat your oven to 350°F (175°C). Grease a 4x8 inch loaf pan with butter or non-stick spray.</li>\n<li>In a large bowl, mash the ripe bananas with a fork until smooth. Stir the melted butter into the mashed bananas.</li>\n<li>Mix in the baking soda and salt. Stir in the sugar, beaten egg, and vanilla extract until combined.</li>\n<li>Gradually add the flour to the mixture and stir just until the flour is incorporated (do not over-mix).</li>\n<li>Pour the batter into the prepared loaf pan and spread it evenly.</li>\n<li>Bake in the preheated oven for 60-65 minutes, or until a toothpick inserted into the center of the bread comes out clean.</li>\n<li>Remove the bread from the oven and let it cool in the pan for about 10 minutes before transferring it to a wire rack to cool completely.</li>\n<li>Slice and serve once cooled or enjoy warm with a bit of butter or jam.</li>\n</ol>\n<strong>Tip:</strong> You can add chocolate chips, nuts, or dried fruit to the batter for a fun twist on this classic recipe."
          },
          {
            name: "Macarons",
            image: "https://images.pexels.com/photos/239578/pexels-photo-239578.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
            recipe: "<h4>Macaron Recipe</h4>\n<h5>Ingredients:</h5>\n<ul>\n<li>1 cup powdered sugar</li>\n<li>1 cup almond flour</li>\n<li>3 large egg whites (room temperature)</li>\n<li>1/4 cup granulated sugar</li>\n<li>1/4 teaspoon cream of tartar</li>\n<li>1/2 teaspoon vanilla extract (or desired flavor)</li>\n<li>Pinch of salt</li>\n<li>Buttercream or ganache filling (for the filling)</li>\n</ul>\n<h5>Instructions:</h5>\n<ol>\n<li>Preheat your oven to 300°F (150°C) and line two baking sheets with parchment paper.</li>\n<li>Sift the powdered sugar and almond flour together to remove any lumps and combine the two into a fine mixture.</li>\n<li>In a clean bowl, beat the egg whites using an electric mixer on medium speed until foamy. Add a pinch of salt and cream of tartar, then increase the speed to high. Gradually add the granulated sugar and continue beating until stiff peaks form (this can take about 5-7 minutes).</li>\n<li>Once stiff peaks are formed, fold in the sifted almond flour and powdered sugar mixture in three batches. Be careful not to deflate the meringue. You want a smooth batter that flows slowly off the spatula.</li>\n<li>Transfer the batter to a piping bag fitted with a round tip and pipe small circles (about 1-1.5 inches in diameter) onto the prepared baking sheets. Space the circles at least an inch apart.</li>\n<li>Tap the baking sheet against the counter a few times to remove air bubbles and to help the macarons spread out slightly.</li>\n<li>Let the macarons sit at room temperature for 30-60 minutes to form a skin on top. The tops should feel dry to the touch before baking.</li>\n<li>Bake the macarons in the preheated oven for 15-18 minutes. Keep a close eye on them and rotate the pans halfway through the baking time for even cooking. The macarons should have risen, formed a foot, and have a smooth top.</li>\n<li>Remove the macarons from the oven and let them cool on the baking sheets for a few minutes before transferring them to a wire rack to cool completely.</li>\n<li>Once cooled, pair similar-sized macarons together. Pipe a small amount of buttercream or ganache onto one half of each pair, then sandwich them together gently.</li>\n<li>For best results, let the macarons sit in the fridge for 24 hours before serving. This allows the flavors to develop and the filling to soften the shells.</li>\n</ol>\n<strong>Tip:</strong> Macarons are a delicate treat, so don't be discouraged if they don't turn out perfectly on the first try. Keep practicing, and you'll get the hang of it!"
          }          
      ]
    },
    {
      category: "Classic Treats",
      items: [
        {
            name: "Pancakes",
            image: "https://images.pexels.com/photos/376464/pexels-photo-376464.jpeg",
            recipe: "<h4>Pancake Recipe</h4>\n<h5>Ingredients:</h5>\n<ul>\n<li>1 cup all-purpose flour</li>\n<li>2 tablespoons sugar</li>\n<li>1 tablespoon baking powder</li>\n<li>1/4 teaspoon salt</li>\n<li>1 large egg</li>\n<li>1 cup milk</li>\n<li>2 tablespoons melted butter</li>\n<li>1 teaspoon vanilla extract</li>\n</ul>\n<h5>Instructions:</h5>\n<ol>\n<li>In a large bowl, whisk together the flour, sugar, baking powder, and salt.</li>\n<li>In a separate bowl, beat the egg and then add the milk, melted butter, and vanilla extract. Whisk until combined.</li>\n<li>Pour the wet ingredients into the dry ingredients and stir until just combined. It's okay if the batter is slightly lumpy; do not overmix.</li>\n<li>Heat a non-stick skillet or griddle over medium heat and lightly grease with butter or oil.</li>\n<li>Pour about 1/4 cup of the pancake batter onto the skillet for each pancake. Cook for about 2-3 minutes until bubbles form on the surface and the edges start to look set.</li>\n<li>Flip the pancake and cook for another 1-2 minutes, or until golden brown on both sides.</li>\n<li>Remove the pancakes from the skillet and keep them warm while you cook the remaining pancakes.</li>\n<li>Serve the pancakes warm with your favorite toppings such as maple syrup, fresh fruit, or whipped cream.</li>\n</ol>\n<strong>Tip:</strong> If you want thicker pancakes, add a little extra flour to the batter. For thinner pancakes, add more milk."
          },
          {
            name: "Waffles",
            image: "https://images.pexels.com/photos/378008/pexels-photo-378008.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
            recipe: "<h4>Waffle Recipe</h4>\n<h5>Ingredients:</h5>\n<ul>\n<li>2 cups all-purpose flour</li>\n<li>2 tablespoons sugar</li>\n<li>2 teaspoons baking powder</li>\n<li>1/2 teaspoon salt</li>\n<li>2 large eggs</li>\n<li>1 3/4 cups milk</li>\n<li>1/2 cup melted butter</li>\n<li>1 teaspoon vanilla extract</li>\n<li>1/4 teaspoon ground cinnamon (optional)</li>\n</ul>\n<h5>Instructions:</h5>\n<ol>\n<li>Preheat your waffle iron according to the manufacturer's instructions.</li>\n<li>In a large bowl, whisk together the flour, sugar, baking powder, salt, and cinnamon (if using).</li>\n<li>In another bowl, beat the eggs, then add the milk, melted butter, and vanilla extract. Stir to combine.</li>\n<li>Pour the wet ingredients into the dry ingredients and stir gently until just combined. The batter may be a little lumpy; do not overmix.</li>\n<li>Lightly grease the waffle iron with cooking spray or a small amount of melted butter.</li>\n<li>Pour an appropriate amount of batter onto the preheated waffle iron (refer to your waffle iron's instructions for how much batter to use).</li>\n<li>Close the waffle iron and cook according to the manufacturer's instructions until the waffles are golden brown and crispy on the outside (usually about 3-5 minutes).</li>\n<li>Carefully remove the waffles from the iron and place them on a plate. Continue cooking the remaining waffles.</li>\n<li>Serve the waffles warm with toppings such as syrup, whipped cream, fresh berries, or a dusting of powdered sugar.</li>\n</ol>\n<strong>Tip:</strong> For crispy waffles, make sure not to overmix the batter, and cook them until they are golden brown and crisp."
          },
          {
            name: "Donuts",
            image: "https://images.pexels.com/photos/205961/pexels-photo-205961.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
            recipe: "<h4>Donut Recipe</h4>\n<h5>Ingredients:</h5>\n<ul>\n<li>2 1/4 teaspoons active dry yeast</li>\n<li>1/4 cup warm water</li>\n<li>1/2 cup warm milk</li>\n<li>1/4 cup sugar</li>\n<li>2 tablespoons butter, melted</li>\n<li>1 teaspoon vanilla extract</li>\n<li>1/2 teaspoon salt</li>\n<li>2 eggs</li>\n<li>3 1/2 cups all-purpose flour</li>\n<li>Vegetable oil, for frying</li>\n<li>1 cup powdered sugar (for glaze)</li>\n<li>2 tablespoons milk (for glaze)</li>\n<li>1/2 teaspoon vanilla extract (for glaze)</li>\n<li>Optional: Sprinkles, cinnamon sugar, or chocolate glaze for topping</li>\n</ul>\n<h5>Instructions:</h5>\n<ol>\n<li>In a small bowl, dissolve the yeast in warm water and let it sit for 5-10 minutes until frothy.</li>\n<li>In a large mixing bowl, combine the warm milk, sugar, butter, vanilla extract, salt, and eggs. Add the yeast mixture and stir to combine.</li>\n<li>Add the flour, one cup at a time, mixing after each addition until the dough forms. Knead the dough on a lightly floured surface for about 5-7 minutes until it becomes smooth and elastic.</li>\n<li>Place the dough in a lightly greased bowl, cover with a clean cloth, and let it rise in a warm place for 1 to 1.5 hours, or until it has doubled in size.</li>\n<li>Once the dough has risen, punch it down and turn it out onto a floured surface. Roll the dough to about 1/2-inch thickness.</li>\n<li>Use a donut cutter or two round cookie cutters (one larger for the outer ring, one smaller for the inner hole) to cut out the donuts.</li>\n<li>Place the donuts on a floured baking sheet and cover with a clean cloth. Let them rise for an additional 30 minutes to 1 hour.</li>\n<li>Heat vegetable oil in a large pot to 350°F (175°C). Carefully fry the donuts in batches, turning them with tongs or a slotted spoon. Fry each donut for about 2 minutes per side, until golden brown.</li>\n<li>Remove the donuts from the oil and place them on a paper towel-lined plate to drain excess oil.</li>\n<li>For the glaze, whisk together powdered sugar, milk, and vanilla extract in a small bowl until smooth. Dip the tops of the donuts into the glaze and let excess drip off.</li>\n<li>Optional: You can top the glazed donuts with sprinkles, cinnamon sugar, or even chocolate glaze if desired.</li>\n<li>Allow the glaze to set before serving.</li>\n</ol>\n<strong>Tip:</strong> For even fluffier donuts, make sure to let the dough rise properly before frying, and fry in small batches to avoid overcrowding the pot."
          },
          {
            name: "Creme Brulee",
            image: "https://images.pexels.com/photos/17628619/pexels-photo-17628619/free-photo-of-sweet-cake-with-fruit.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
            recipe: "<h4>Creme Brulee Recipe</h4>\n<h5>Ingredients:</h5>\n<ul>\n<li>2 cups heavy cream</li>\n<li>1 vanilla bean (or 1 tablespoon vanilla extract)</li>\n<li>5 large egg yolks</li>\n<li>1/2 cup granulated sugar</li>\n<li>1/4 cup brown sugar (for caramelizing)</li>\n</ul>\n<h5>Instructions:</h5>\n<ol>\n<li>Preheat the oven to 325°F (163°C) and arrange 4-6 ramekins in a baking dish.</li>\n<li>In a medium saucepan, heat the heavy cream and vanilla bean (or vanilla extract) over medium heat. If using a vanilla bean, split it in half, scrape the seeds into the cream, and add the pod as well. Heat the mixture until it begins to steam, but do not let it boil. Remove from heat and let steep for 10-15 minutes.</li>\n<li>Meanwhile, whisk the egg yolks and granulated sugar together in a bowl until the mixture becomes pale and thick.</li>\n<li>Slowly pour the warm cream mixture into the egg yolk mixture, whisking constantly to avoid scrambling the eggs. Once combined, strain the mixture through a fine mesh sieve into a clean bowl to remove the vanilla bean pod and any curdled bits.</li>\n<li>Pour the custard mixture evenly into the prepared ramekins.</li>\n<li>Carefully pour hot water into the baking dish around the ramekins, ensuring that the water comes halfway up the sides of the ramekins.</li>\n<li>Bake the custard in the preheated oven for 40-45 minutes, or until the edges are set but the center is still slightly wobbly. The custard should jiggle when gently shaken.</li>\n<li>Remove the ramekins from the water and let them cool to room temperature. Then refrigerate for at least 2 hours or overnight for best results.</li>\n<li>Just before serving, sprinkle an even layer of brown sugar over the top of each custard.</li>\n<li>Using a kitchen torch, caramelize the sugar by holding the torch a few inches away from the surface and moving it in circular motions until the sugar turns golden and forms a crispy, caramelized top. Alternatively, you can place the ramekins under the broiler for 1-2 minutes, watching closely to avoid burning the sugar.</li>\n<li>Allow the creme brulee to sit for a minute to cool slightly before serving. Enjoy the creamy, crunchy contrast of the dessert!</li>\n</ol>\n<strong>Tip:</strong> For a smoother custard, make sure to strain the mixture before baking to remove any solid bits, especially when using a vanilla bean."
          }          
      ]
    }
  ];

const dessertContainer = document.getElementById("dessertCards");

desserts.forEach(group => {
  group.items.forEach(dessert => {
    const col = document.createElement("div");
    col.className = "col-md-6 col-lg-4 mb-4";
    col.innerHTML = `
      <div class="card h-100 shadow-sm">
        <img src="${dessert.image}" class="card-img-top" alt="${dessert.name}">
        <div class="card-body">
          <h5 class="card-title">${dessert.name}</h5>
          <p class="card-text">${group.category}</p>
          <button class="btn btn-primary" onclick='showRecipe("${dessert.name.replace(/"/g, "&quot;")}")'>View Recipe</button>
        </div>
      </div>
    `;
    dessertContainer.appendChild(col);
  });
});

function showRecipe(name) {
  for (const group of desserts) {
    for (const dessert of group.items) {
      if (dessert.name === name) {
        document.getElementById("recipeModalLabel").innerText = dessert.name;
        document.getElementById("recipeContent").innerHTML = dessert.recipe;
        new bootstrap.Modal(document.getElementById("recipeModal")).show();
        return;
      }
    }
  }
}
